@baseUrl = http://127.0.0.1:8000/




###
POST {{baseUrl}}api/register HTTP/1.1
content-type: application/json

{
    "username": "chrisred",
    "email": "chrisred@gmail.com",
    "password": "chrisred17."
}