# Generated by Django 4.1.1 on 2023-08-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=70)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
        ),
    ]
