# Generated by Django 4.1.10 on 2023-08-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Sample',
        ),
    ]
