openapi: 3.0.3
info:
  title: Scrapping API
  version: 1.5.1
  description: 'Based to locate websites and getting relevant authors in social medias
    (Dev: Christian Soledispa)'
paths:
  /api/auths:
    get:
      operationId: auths_retrieve
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: auths_create
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: auths_destroy
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/auths/{id}:
    get:
      operationId: auths_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: auths_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: auths_destroy_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/auths/superuser:
    get:
      operationId: auths_superuser_retrieve
      tags:
      - auths
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
