# Generated by Django 4.1.1 on 2023-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
