# Generated by Django 4.1.1 on 2023-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_alter_appuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
