# Generated by Django 4.1.1 on 2023-08-19 21:31

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0003_alter_appuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="user_id",
            field=djongo.models.fields.ObjectIdField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
