# Generated by Django 4.1.1 on 2023-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0004_alter_appuser_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
